### ISSUE TITLE
Subsequent clicks cause the full menu to flash on screen before the reveal animation

### ISSUE THREAD

**Issue by chrisconover** [Polymer/paper-dropdown-menu#45]
The paper-dropdown-menu reveal animation works correctly on the first click, but subsequent clicks cause the full menu to flash on screen before the reveal animation begins.

I've made a basic example at http://jsbin.com/lawuli

Here's a screencast demonstrating the issue as well: https://drive.google.com/file/d/0B8IK6wolRJizSEV0MmhXNWJFc0k/view?usp=sharing

**Comment by morethanreal** [comment]
I think it's due to this bug: web-animations/web-animations-next#260

**Comment by alancutter** [comment]
The web-animation-js bug looks to be fixed in v1.0.5 according to web-animations/web-animations-next#260 however core-animation v0.5 is still using web-animations-js [v1.0.1](https://github.com/alancutter/core-animation/blob/0.5.2/bower.json). Should its v0.5 bower be updated to point at web-animations-js#~1.0.5?

**Comment by morethanreal** [comment]
Updated in Polymer/core-animation@ce0a08e6992f50109f5d6d5e4fa2cd65bc7726f1

**Comment by richieb** [comment]
This problem still exists, even after updating web-animations to 1.0.5 and core-animations to 0.5.4. Could someone confirm that it has indeed been fixed?

**Comment by pflannery** [comment]
This is working for me locally @ core-animations 0.5.4 and web-animations 1.0.5..but it's not working at https://www.polymer-project.org/components/paper-dropdown-menu/demo.html

**Comment by WrinklyNinja** [comment]
I'm still experiencing this with Polymer 0.5.4 (and web-animations 1.0.5) too.

**Comment by RobertLowe** [comment]
@morethanreal Can confirm as well. This is still happening on 0.5.4 & 1.0.5

Can we reopen the issue?

**Comment by WrinklyNinja** [comment]
After some more investigation, this bug only manifests under Chromium 40 and earlier. It's fixed in Chromium 41 (tested using the Chromium Embedded Framework branch 2272) and 42 (tested using the Chrome Canary).

**Comment by rjwright** [comment]
I'm wondering if this could be a result of this bug https://github.com/web-animations/web-animations-next/issues/278 (which turned out to be a Chrome 40 issue, not a Web Animations Polyfill issue).

**Comment by morethanreal** [comment]
@rjwright Is there a workaround for Chrome 40?

**Comment by RobertLowe** [comment]
@morethanreal https://github.com/Polymer/paper-dropdown/issues/6#issuecomment-72582257 or https://github.com/Polymer/paper-dropdown/issues/6#issuecomment-72536847 insuring the state is immediately set or reverted worked for me.

As for a workaround I have nothing else to offer, cheers.

**Comment by morethanreal** [comment]
I'm resetting the dropdown background in Polymer/paper-dropdown@62a37d5, which seems to fix this issue.

**Comment by RobertLowe** [comment]
@morethanreal you're awesome! :+1:

**Comment by rjwright** [comment]
@morethanreal I will have a look Today to see if we can put a workaround in the polyfill.
