### ISSUE TITLE
Menu does not render over if there is no room bottom

### ISSUE THREAD

**Issue by mmacedoeu** [Polymer/paper-dropdown-menu#47]
![image](https://cloud.githubusercontent.com/assets/4959023/5617338/d413a6ca-94f4-11e4-98bf-dc517b569ec9.png)

**Comment by morethanreal** [comment]
The dropdown defaults to aligning to the top and left edges of the control. You can set those properties on `paper-dropdown` if you want it to align differently, e.g. `<paper-dropdown valign="bottom">`.

**Comment by mmacedoeu** [comment]
When there is no room bottom it should render automatically above:

![image](https://cloud.githubusercontent.com/assets/4959023/5902824/eb549c38-a564-11e4-8ac4-f5458d49008e.png)
