### ISSUE TITLE
dropdowns for Polymer 1.0?

### ISSUE THREAD

**Issue by dough10** [Polymer/paper-dropdown-menu#63]
any plans to update the dropdown elements to polymer 1.0?

**Comment by yawenzhongyuan** [comment]
want it,too!

**Comment by grokys** [comment]
+1

**Comment by fredpedro** [comment]
When you view the source of polymer-project.org, it is very apparent that they are using paper-dropdown-menu. But when I try to use it on my Polymer version 1.0 project, it just doesn't work. Perhaps there is a replacement for this element in version 1.

**Comment by SmokyBob** [comment]
`paper-dropdown-menu` is being upgraded to 1.0
You can follow `paper-elements` roadmap [here](https://github.com/PolymerElements/paper-elements)

I guess the work is currently in a private branch/repo and will be published under the PolymerElements when ready (patiently waiting for it too to upgrade a couple of apps)

**Comment by notthetup** [comment]
:+1:

**Comment by tonytonyjan** [comment]
:+1:

**Comment by richardhundt** [comment]
:+1:

**Comment by lcasartelli** [comment]
+1

**Comment by notwaldorf** [comment]
Closing this, as it's technically a duplicate of https://github.com/PolymerElements/paper-elements/issues/17. This is an element we're currently working on, and it should be available soon! :)

**Comment by Sinjins** [comment]
+1

**Comment by zenorocha** [comment]
FYI this element has been released couple hours ago: https://github.com/PolymerElements/paper-dropdown-menu/releases
