### ISSUE TITLE
paper-dropdown-menu is not working after upgrade to Polymer 2.0

### ISSUE THREAD

**Issue by DominicWrege** [Polymer/paper-dropdown-menu#79]
After the upgrade from Polymer v1.4 to v2.0 the paper-dropdown-menu stoped working. I am using it inside a paper-dialog. I have to use the paper-listbox instead of the paper-menu because there is no 2.0-preview branche for it. I checked the dropdown-menu with the web inspector and the list wasn't empty. It seems to me that the click event does not his job. I am getting no console Error.

**Code**

```
<paper-dropdown-menu label="Gruppenbuchstabe">
    <paper-listbox class="dropdown-content">
       <paper-item>This</paper-item>
       <paper-item>is</paper-item>
       <paper-item>not</paper-item>
       <paper-item>working</paper-item>
   </paper-listbox>
</paper-dropdown-menu>
```

**Demo**

![screen capture on 2017-04-15 at 12-46-14](https://cloud.githubusercontent.com/assets/7389000/25063038/a07dd44c-21d9-11e7-9f27-5f84d80ec14d.gif)

**Comment by notwaldorf** [comment]
This issue was moved to PolymerElements/paper-dropdown-menu#242
